/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 public/LEAPR_merge_16.glb
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/LEAPR_merge_16.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="patita_main" position={[0, 9.24, 0]} rotation={[0, 0.17, 0]}>
          <mesh name="Patita_V1001_Curve004_cell162" geometry={nodes.Patita_V1001_Curve004_cell162.geometry} material={nodes.Patita_V1001_Curve004_cell162.material} position={[0.26, -6.73, 4.89]} />
          <mesh name="Patita_V1001_Curve004_cell166" geometry={nodes.Patita_V1001_Curve004_cell166.geometry} material={nodes.Patita_V1001_Curve004_cell166.material} position={[5.67, -14.67, 4.94]} />
          <mesh name="Patita_V1001_Curve004_cell167" geometry={nodes.Patita_V1001_Curve004_cell167.geometry} material={nodes.Patita_V1001_Curve004_cell167.material} position={[1.01, -20.76, 4.95]} />
          <mesh name="Patita_V1001_Curve004_cell168" geometry={nodes.Patita_V1001_Curve004_cell168.geometry} material={nodes.Patita_V1001_Curve004_cell168.material} position={[-1.34, -8.63, 5.04]} />
          <mesh name="Patita_V1001_Curve004_cell169" geometry={nodes.Patita_V1001_Curve004_cell169.geometry} material={nodes.Patita_V1001_Curve004_cell169.material} position={[3.59, -9.62, 4.96]} />
          <mesh name="Patita_V1001_Curve004_cell171" geometry={nodes.Patita_V1001_Curve004_cell171.geometry} material={nodes.Patita_V1001_Curve004_cell171.material} position={[-0.96, -5.32, 4.75]} />
          <mesh name="Patita_V1001_Curve004_cell172" geometry={nodes.Patita_V1001_Curve004_cell172.geometry} material={nodes.Patita_V1001_Curve004_cell172.material} position={[-3.65, -8.62, 4.97]} />
          <mesh name="Patita_V1001_Curve004_cell173" geometry={nodes.Patita_V1001_Curve004_cell173.geometry} material={nodes.Patita_V1001_Curve004_cell173.material} position={[0.51, -4.16, 5]} />
          <mesh name="Patita_V1001_Curve004_cell174" geometry={nodes.Patita_V1001_Curve004_cell174.geometry} material={nodes.Patita_V1001_Curve004_cell174.material} position={[-0.38, -10.1, 4.98]} />
          <mesh name="Patita_V1001_Curve004_cell177" geometry={nodes.Patita_V1001_Curve004_cell177.geometry} material={nodes.Patita_V1001_Curve004_cell177.material} position={[-6.99, -11.37, 4.94]} />
          <mesh name="Patita_V1001_Curve004_cell179" geometry={nodes.Patita_V1001_Curve004_cell179.geometry} material={nodes.Patita_V1001_Curve004_cell179.material} position={[-2.35, -13.16, 4.9]} />
          <mesh name="Patita_V1001_Curve004_cell180" geometry={nodes.Patita_V1001_Curve004_cell180.geometry} material={nodes.Patita_V1001_Curve004_cell180.material} position={[0.45, -12.89, 5.02]} />
          <mesh name="Patita_V1001_Curve004_cell182" geometry={nodes.Patita_V1001_Curve004_cell182.geometry} material={nodes.Patita_V1001_Curve004_cell182.material} position={[4.19, -3.69, 4.98]} />
          <mesh name="Patita_V1001_Curve004_cell183" geometry={nodes.Patita_V1001_Curve004_cell183.geometry} material={nodes.Patita_V1001_Curve004_cell183.material} position={[-0.5, -0.27, 4.97]} />
          <mesh name="Patita_V1001_Curve004_cell184" geometry={nodes.Patita_V1001_Curve004_cell184.geometry} material={nodes.Patita_V1001_Curve004_cell184.material} position={[3.13, -8.06, 4.96]} />
          <mesh name="Patita_V1001_Curve004_cell185" geometry={nodes.Patita_V1001_Curve004_cell185.geometry} material={nodes.Patita_V1001_Curve004_cell185.material} position={[-1.02, -13.3, 4.95]} />
          <mesh name="Patita_V1001_Curve004_cell186" geometry={nodes.Patita_V1001_Curve004_cell186.geometry} material={nodes.Patita_V1001_Curve004_cell186.material} position={[-3.35, -12.5, 4.74]} />
          <mesh name="Patita_V1001_Curve004_cell187" geometry={nodes.Patita_V1001_Curve004_cell187.geometry} material={nodes.Patita_V1001_Curve004_cell187.material} position={[-11.87, -4.03, 4.6]} />
          <mesh name="Patita_V1001_Curve004_cell189" geometry={nodes.Patita_V1001_Curve004_cell189.geometry} material={nodes.Patita_V1001_Curve004_cell189.material} position={[8.45, -7.49, 4.31]} />
          <mesh name="Patita_V1001_Curve004_cell190" geometry={nodes.Patita_V1001_Curve004_cell190.geometry} material={nodes.Patita_V1001_Curve004_cell190.material} position={[1.56, -4.96, 4.88]} />
          <mesh name="Patita_V1001_Curve004_cell191" geometry={nodes.Patita_V1001_Curve004_cell191.geometry} material={nodes.Patita_V1001_Curve004_cell191.material} position={[-1.63, -17.08, 4.97]} />
          <mesh name="Patita_V1001_Curve004_cell193" geometry={nodes.Patita_V1001_Curve004_cell193.geometry} material={nodes.Patita_V1001_Curve004_cell193.material} position={[-1.36, -2.86, 5.2]} />
          <mesh name="Patita_V1001_Curve004_cell194" geometry={nodes.Patita_V1001_Curve004_cell194.geometry} material={nodes.Patita_V1001_Curve004_cell194.material} position={[1.4, -0.75, 4.96]} />
          <mesh name="Patita_V1001_Curve004_cell195" geometry={nodes.Patita_V1001_Curve004_cell195.geometry} material={nodes.Patita_V1001_Curve004_cell195.material} position={[-5.52, -9.23, 5.17]} />
          <mesh name="Patita_V1001_Curve004_cell196" geometry={nodes.Patita_V1001_Curve004_cell196.geometry} material={nodes.Patita_V1001_Curve004_cell196.material} position={[2.72, -5.87, 5.03]} />
          <mesh name="Patita_V1001_Curve004_cell198" geometry={nodes.Patita_V1001_Curve004_cell198.geometry} material={nodes.Patita_V1001_Curve004_cell198.material} position={[-5.64, -7.22, 5.01]} />
          <mesh name="Patita_V1001_Curve004_cell199" geometry={nodes.Patita_V1001_Curve004_cell199.geometry} material={nodes.Patita_V1001_Curve004_cell199.material} position={[-6.31, -13.5, 4.95]} />
          <mesh name="Patita_V1001_Curve004_cell200" geometry={nodes.Patita_V1001_Curve004_cell200.geometry} material={nodes.Patita_V1001_Curve004_cell200.material} position={[-3.94, -1.79, 4.99]} />
          <mesh name="Patita_V1001_Curve004_cell203" geometry={nodes.Patita_V1001_Curve004_cell203.geometry} material={nodes.Patita_V1001_Curve004_cell203.material} position={[1.26, -5.94, 5.17]} />
          <mesh name="Patita_V1001_Curve004_cell204" geometry={nodes.Patita_V1001_Curve004_cell204.geometry} material={nodes.Patita_V1001_Curve004_cell204.material} position={[2.18, -14.62, 4.99]} />
          <mesh name="Patita_V1001_Curve004_cell205" geometry={nodes.Patita_V1001_Curve004_cell205.geometry} material={nodes.Patita_V1001_Curve004_cell205.material} position={[-6.12, -10.79, 5.02]} />
          <mesh name="Patita_V1001_Curve004_cell209" geometry={nodes.Patita_V1001_Curve004_cell209.geometry} material={nodes.Patita_V1001_Curve004_cell209.material} position={[1.88, -8.84, 4.93]} />
          <mesh name="Patita_V1001_Curve004_cell210" geometry={nodes.Patita_V1001_Curve004_cell210.geometry} material={nodes.Patita_V1001_Curve004_cell210.material} position={[-2.54, -11.22, 4.98]} />
          <mesh name="Patita_V1001_Curve004_cell212" geometry={nodes.Patita_V1001_Curve004_cell212.geometry} material={nodes.Patita_V1001_Curve004_cell212.material} position={[9.53, -5.49, 4.73]} />
          <mesh name="Patita_V1001_Curve004_cell213" geometry={nodes.Patita_V1001_Curve004_cell213.geometry} material={nodes.Patita_V1001_Curve004_cell213.material} position={[-1.09, -9.07, 4.84]} />
          <mesh name="Patita_V1001_Curve004_cell214" geometry={nodes.Patita_V1001_Curve004_cell214.geometry} material={nodes.Patita_V1001_Curve004_cell214.material} position={[2.18, -11.75, 4.93]} />
          <mesh name="Patita_V1001_Curve004_cell215" geometry={nodes.Patita_V1001_Curve004_cell215.geometry} material={nodes.Patita_V1001_Curve004_cell215.material} position={[-0.36, -5.6, 4.95]} />
          <mesh name="Patita_V1001_Curve004_cell216" geometry={nodes.Patita_V1001_Curve004_cell216.geometry} material={nodes.Patita_V1001_Curve004_cell216.material} position={[-10.66, -4.55, 5.01]} />
          <mesh name="Patita_V1001_Curve004_cell218" geometry={nodes.Patita_V1001_Curve004_cell218.geometry} material={nodes.Patita_V1001_Curve004_cell218.material} position={[-8.39, -12.1, 5.01]} />
          <mesh name="Patita_V1001_Curve004_cell219" geometry={nodes.Patita_V1001_Curve004_cell219.geometry} material={nodes.Patita_V1001_Curve004_cell219.material} position={[-2.77, -6.99, 4.98]} />
          <mesh name="Patita_V1001_Curve004_cell220" geometry={nodes.Patita_V1001_Curve004_cell220.geometry} material={nodes.Patita_V1001_Curve004_cell220.material} position={[-5.03, -8.71, 4.89]} />
          <mesh name="Patita_V1001_Curve004_cell221" geometry={nodes.Patita_V1001_Curve004_cell221.geometry} material={nodes.Patita_V1001_Curve004_cell221.material} position={[-4.72, -12.56, 5.01]} />
          <mesh name="Patita_V1001_Curve004_cell222" geometry={nodes.Patita_V1001_Curve004_cell222.geometry} material={nodes.Patita_V1001_Curve004_cell222.material} position={[5.21, -11.56, 4.95]} />
          <mesh name="Patita_V1001_Curve004_cell223" geometry={nodes.Patita_V1001_Curve004_cell223.geometry} material={nodes.Patita_V1001_Curve004_cell223.material} position={[1.4, -7.25, 4.73]} />
          <mesh name="Patita_V1001_Curve004_cell224" geometry={nodes.Patita_V1001_Curve004_cell224.geometry} material={nodes.Patita_V1001_Curve004_cell224.material} position={[-9.7, -13.32, 4.93]} />
          <mesh name="Patita_V1001_Curve004_cell225" geometry={nodes.Patita_V1001_Curve004_cell225.geometry} material={nodes.Patita_V1001_Curve004_cell225.material} position={[-4.48, -11.08, 4.92]} />
          <mesh name="Patita_V1001_Curve004_cell227" geometry={nodes.Patita_V1001_Curve004_cell227.geometry} material={nodes.Patita_V1001_Curve004_cell227.material} position={[0.93, -17.12, 4.97]} />
          <mesh name="Patita_V1001_Curve004_cell229" geometry={nodes.Patita_V1001_Curve004_cell229.geometry} material={nodes.Patita_V1001_Curve004_cell229.material} position={[-3.34, -14.45, 4.96]} />
          <mesh name="Patita_V1001_Curve004_cell230" geometry={nodes.Patita_V1001_Curve004_cell230.geometry} material={nodes.Patita_V1001_Curve004_cell230.material} position={[-0.98, -14.71, 4.96]} />
          <mesh name="Patita_V1001_Curve004_cell231" geometry={nodes.Patita_V1001_Curve004_cell231.geometry} material={nodes.Patita_V1001_Curve004_cell231.material} position={[-10.07, -10.45, 4.67]} />
          <mesh name="Patita_V1001_Curve004_cell232" geometry={nodes.Patita_V1001_Curve004_cell232.geometry} material={nodes.Patita_V1001_Curve004_cell232.material} position={[0.26, -15.2, 4.91]} />
          <mesh name="Patita_V1001_Curve004_cell234" geometry={nodes.Patita_V1001_Curve004_cell234.geometry} material={nodes.Patita_V1001_Curve004_cell234.material} position={[1.33, -10.11, 4.97]} />
          <mesh name="Patita_V1001_Curve004_cell235" geometry={nodes.Patita_V1001_Curve004_cell235.geometry} material={nodes.Patita_V1001_Curve004_cell235.material} position={[-2.4, -4.26, 4.99]} />
          <mesh name="Patita_V1001_Curve004_cell236" geometry={nodes.Patita_V1001_Curve004_cell236.geometry} material={nodes.Patita_V1001_Curve004_cell236.material} position={[0.72, -8.18, 4.98]} />
          <mesh name="Patita_V1001_Curve004_cell240" geometry={nodes.Patita_V1001_Curve004_cell240.geometry} material={nodes.Patita_V1001_Curve004_cell240.material} position={[10.31, -14.17, 3.57]} />
          <mesh name="Patita_V1001_Curve004_cell157" geometry={nodes.Patita_V1001_Curve004_cell157.geometry} material={nodes.Patita_V1001_Curve004_cell157.material} morphTargetDictionary={nodes.Patita_V1001_Curve004_cell157.morphTargetDictionary} morphTargetInfluences={nodes.Patita_V1001_Curve004_cell157.morphTargetInfluences} position={[8.39, -46.76, -0.11]} />
        </group>
        <mesh name="CuboProcess001" geometry={nodes.CuboProcess001.geometry} material={nodes.CuboProcess001.material} position={[0, -668.33, 0]} rotation={[0.01, 0.01, 0.23]} scale={-30.36} />
        <mesh name="CuboProcess002" geometry={nodes.CuboProcess002.geometry} material={nodes.CuboProcess002.material} position={[0, -668.33, 0]} rotation={[0.01, 0.01, 0.23]} scale={-30.36} />
        <mesh name="CuboProcess003" geometry={nodes.CuboProcess003.geometry} material={nodes.CuboProcess003.material} position={[0, -668.33, 0]} rotation={[0.01, 0.01, 0.23]} scale={-30.36} />
        <mesh name="CuboProcess004" geometry={nodes.CuboProcess004.geometry} material={nodes.CuboProcess004.material} position={[0, -668.33, 0]} rotation={[0.01, 0.01, 0.23]} scale={-30.36} />
        <mesh name="CuboProcess005" geometry={nodes.CuboProcess005.geometry} material={nodes.CuboProcess005.material} position={[0, -668.33, 0]} rotation={[0.01, 0.01, 0.23]} scale={-30.36} />
        <mesh name="CuboProcess006" geometry={nodes.CuboProcess006.geometry} material={nodes.CuboProcess006.material} position={[0, -668.33, 0]} rotation={[0.01, 0.01, 0.23]} scale={-30.36} />
        <mesh name="CuboProcess007" geometry={nodes.CuboProcess007.geometry} material={nodes.CuboProcess007.material} position={[0, -668.33, 0]} rotation={[0.01, 0.01, 0.23]} scale={-30.36} />
        <mesh name="CuboProcess008" geometry={nodes.CuboProcess008.geometry} material={nodes.CuboProcess008.material} position={[0, -668.33, 0]} rotation={[0.01, 0.01, 0.23]} scale={-30.36} />
        <group name="DISTRITO_DCL" position={[47.09, -377.05, -26.34]} rotation={[-Math.PI / 2, -0.22, Math.PI / 2]} scale={4.98}>
          <mesh name="Plane096" geometry={nodes.Plane096.geometry} material={nodes.Plane096.material} />
          <mesh name="Plane096_1" geometry={nodes.Plane096_1.geometry} material={nodes.Plane096_1.material} />
          <mesh name="Plane096_2" geometry={nodes.Plane096_2.geometry} material={nodes.Plane096_2.material} />
          <mesh name="Plane096_3" geometry={nodes.Plane096_3.geometry} material={nodes.Plane096_3.material} />
          <mesh name="Plane096_4" geometry={nodes.Plane096_4.geometry} material={nodes.Plane096_4.material} />
          <mesh name="Plane096_5" geometry={nodes.Plane096_5.geometry} material={nodes.Plane096_5.material} />
          <mesh name="Plane096_6" geometry={nodes.Plane096_6.geometry} material={nodes.Plane096_6.material} />
          <mesh name="Plane096_7" geometry={nodes.Plane096_7.geometry} material={nodes.Plane096_7.material} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/LEAPR_merge_16.glb')
